### ISSUE TITLE
Peer ID Invalid

### ISSUE THREAD

**Issue by abangkis** [rubenlagus/Deepthought#5]
Hi, first thanks for creating this project. Second, when I tried running this project, and sending a message to this user I've got Peer id invalid error. Could you help me what the problem is? I already set up the project with my own id, hash, and phone number. And also the table in the database is created but it's all empty. 

Thanks.

[27_6_2016_17:27:56] {SEVERE} KERNELCOMM - java.util.concurrent.ExecutionException: org.telegram.api.engine.RpcException: PEER_ID_INVALID	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.telegram.bot.kernel.KernelComm.doRpcCallSync(KernelComm.java:184)
	at org.telegram.bot.kernel.KernelComm.performMarkAsReadInternal(KernelComm.java:654)
	at org.telegram.bot.kernel.KernelComm.performMarkAsRead(KernelComm.java:632)
	at org.telegram.plugins.echo.handlers.MessageHandler.handleMessageInternal(MessageHandler.java:56)
	at org.telegram.plugins.echo.handlers.MessageHandler.handleMessage(MessageHandler.java:46)
	at org.telegram.plugins.echo.handlers.CustomUpdatesHandler.onTLUpdateShortMessageCustom(CustomUpdatesHandler.java:61)
	at org.telegram.bot.handlers.UpdatesHandlerBase.onTLUpdateShortMessage(UpdatesHandlerBase.java:264)
	at org.telegram.bot.handlers.UpdatesHandlerBase.processUpdate(UpdatesHandlerBase.java:107)
	at org.telegram.bot.kernel.MainHandler$UpdateHandlerThread.run(MainHandler.java:301)

**Comment by ilhamiarie** [comment]
me too

**Comment by rubenlagus** [comment]
This error means that you are unable do access to that chat or user, can't know the reason with this only.

Btw, the api was moved to: https://github.com/rubenlagus/TelegramApi

**Comment by ibgithub** [comment]
It is because the sender number is not recognize by your phone, save the number as your new contact, then the problem is solved
